### ISSUE TITLE
Enforcing sending request to Convead.io

### ISSUE THREAD

**Issue by mihan007** [Convead/convead_api_php_client#1]
I've tried to use this code to send "purchase" event when I'm got callback from payment system. The issue is that payment system send callback with no User Agent defined and when I was trying to send request to your api it just did nothing and return `true` (see https://github.com/Convead/convead_api_php_client/blob/master/ConveadTracker.php#L391)

I realized that just after examining your sourcebase. What I'd like to have here:
- just throw some error like "UA isn't supported" for automatic tracking to see it at code and understand that something goes wrong;
- OR add additional param that force you code to disable UA checking;

My current solution is dirty (I didn't want to change your code):

``` php
$previousUA = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : null;
$_SERVER['HTTP_USER_AGENT'] = 'Mozilla/5.0 (X11; U; Linux x86; en-US; rv:1.9.0.5) Gecko';

// do all Convead tracking related stuff...

if ($previousUA !== null) {
   $_SERVER['HTTP_USER_AGENT'] = $previousUA;
} else {
   unset($_SERVER['HTTP_USER_AGENT']);
}
```

**Comment by rostber** [comment]
Код разрабатывался под технические условия при которых он должен был вызываться при запросе от посетителя.
В условиях того, что события покупки могут отправляться не от пользователя, а от платежной системы, имеет смысл отказаться от данной проверки.
Внесли изменения в код 5233d743ecf2373bbb47bf2f6eca9b9e091c7302 убрали данное условие.

**Comment by mihan007** [comment]
Спасибо! Вопросов больше нет.
